sudo: required
services: 
    - docker

before_install: 
    - docker build -t kajari/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true kajari/react-test npm test 

after success: 
    - docker build -t kajari/multi-client ./client
    - docker build -t kajari/multi-nginx ./nginx
    - docker build -t kajari/multi-server ./server
    - docker build -t kajari/multi-worker ./worker

#login to docker cli
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker login -u “$DOCKER_ID” -p “$DOCKER_PASSWORD” docker.io
    - docker tag kajari/multi-client $DOCKER_ID/kajari/multi-client:$TRAVIS_BUILD_NUMBER
    #take these images and push to docker hub
    - docker push $DOCKER_ID/kajari/multi-client:$TRAVIS_BUILD_NUMBER
   # - docker push kajari/multi-nginx
    #- docker push kajari/multi-server
    #- docker push kajari/multi-worker