sudo: required
services: 
    - docker

before_install: 
    - docker build -t kajari/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true kajari/react-test npm test 

after success: 
    - docker build -t kajariagrawal/multi-client ./client #the tag has to be identical to the docker id for pushing successfully
    - docker build -t kajariagrawal/multi-nginx ./nginx
    - docker build -t kajariagrawal/multi-server ./server
    - docker build -t kajariagrawal/multi-worker ./worker

#login to docker cli
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin this is another method
    - docker login -u “$DOCKER_ID” -p “$DOCKER_PASSWORD” docker.io
    #take these images and push to docker hub
    - docker push kajariagrawal/multi-client
    - docker push kajariagrawal/multi-nginx
    - docker push kajariagrawal/multi-server
    - docker push kajariagrawal/multi-worker